---

## - Set-up Docker Repository
- name: apt-get update
  apt:
    update_cache: yes

- name: Install the package "{{ item }}"
  apt:
    name: "{{ item }}"
    state: present
  loop: 
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- name: Add Docker repository key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Apt Repository
  command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"


## - Install Docker Engine
- name: apt-get update
  apt:
    update_cache: yes
- name: Install the package "{{ item }}"
  apt:
    name: "{{ item }}"
    state: present
  loop: 
  - docker-ce 
  - docker-ce-cli 
  - containerd.io

- name: Start service docker, if not started
  service:
    name: docker
    state: started