tasks:
  - name: Install Calico
    command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
    
  - name: Install resources
    command: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml

  - name: wait for pods to come up
    shell: kubectl get pods -n calico-system -o json
    register: kubectl_get_pods
    until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]