# -------------------- #
# --- Pre-required --- #
# -------------------- #
- name: Pre-required
  hosts: localhost
  tasks:
  - name: Disable Swap
    command: swapoff -a
    
# -------------- #
# --- Docker --- #
# -------------- #
- name: Docker
  hosts: localhost
  roles:
  - delete_docker # Delete old instances
  - install_docker # Install Docker Engine

# ------------------ #
# --- Kubernetes --- #
# ------------------ #
## - Install kubeadm
- name: Kubernetes
  hosts: localhost
  roles:
  - install_k8s
  - k8s_cluster

# -------------- #
# --- Calico --- #
# -------------- #
- name: Install Calico
  hosts: localhost
  tasks:
  - name: Install Calico
    command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
  - name: Install resources
    command: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
  - name: wait for pods to come up
    shell: kubectl get pods -n calico-system -o json
    register: kubectl_get_pods
    until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

# ------------------ #
# --- Kubernetes --- #
# ------------------ #
## - Untaint master node
- name: Kubernetes - Untaint master node
  hosts: localhost
  tasks:
  - name: untaint master node
    command: kubectl taint nodes --all node-role.kubernetes.io/master-