---

# -------------------- #
# --- Pre-required --- #
# -------------------- #
- hosts: localhost
  tasks:
  - name: Disable Swap
    command: swapoff -a
    
# -------------- #
# --- Docker --- #
# -------------- #
- hosts: localhost
  roles:
  - delete_docker # Delete old instances
  - install_docker # Install Docker Engine

# ------------------ #
# --- Kubernetes --- #
# ------------------ #
- hosts: localhost
  roles:
  - install_k8s
  - k8s_cluster
  - install_calico


# ------------------ #
# --- Kubernetes --- #
# ------------------ #
## - Untaint master node
- hosts: localhost
  tasks:
  - name: untaint master node
    command: kubectl taint nodes --all node-role.kubernetes.io/master-