- name: Uninstall Docker & Kubernetes
  hosts: localhost
  tasks:
  - name: Purge "{{ item }}"
    command: apt-get purge "{{ item }}"
    loop:
    - kubeadm 
    - kubectl 
    - kubelet 
    - kubernetes-cni 
    - kube*   
  - name: Clean unwanted old stuff
    apt:
      autoremove: yes
  - name: Remove Kubernetes config files
    command: rm -rf ~/.kube

  roles:
  - reset_cluster

  - delete_docker